'use strict'
// auto-generated by boundation, do not update manually
/** @type {typeof import("./edition-types/test.d.ts") } */
module.exports = require('editions').requirePackage(__dirname, require, 'test.js')