name: bevry
'on':
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - '10'
          - '12'
          - '14'
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ contains('macos-latest windows-latest', matrix.os) }}
    steps:
      - uses: actions/checkout@v2
      - name: Install desired Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm run our:setup
      - run: npm run our:compile
      - run: npm run our:verify
      - name: Install targeted Node.js
        if: ${{ matrix.node != 14 }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm test
  publish:
    if: ${{ github.event_name == 'push' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install desired Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm run our:setup
      - run: npm run our:compile
      - run: npm run our:meta
      - name: publish to npm
        uses: bevry-actions/npm@v1.1.0
        with:
          npmAuthToken: ${{ secrets.NPM_AUTH_TOKEN }}
          npmBranchTag: ':next'
      - name: publish to surge
        uses: bevry-actions/surge@v1.0.3
        with:
          surgeLogin: ${{ secrets.SURGE_LOGIN }}
          surgeToken: ${{ secrets.SURGE_TOKEN }}
